server:
    port: 8085

spring:
    rabbitmq:
        addresses: localhost
        port: 5672
        username: guest
        password: guest
        publisher-confirms: true
        publisherReturns: true
        listener:
          simple:
            acknowledge-mode: manual
        virtual-host: /yuanwj
        requested-heartbeat:
    application:
        name: spring-mq
mq:
    topicExchange: yuanwj
    queueName: test
    routingKey: yuanwj.#
