server:
    port: 8081

spring:
    application:
        name: spring-mq

    rabbitmq:
        addresses: localhost
        port: 5672
        username: guest
        password: guest
        publisher-confirms: true
        publisherReturns: true
        listener:
          simple:
            acknowledge-mode: manual